### PR TITLE
Hug.py: Make someone feel good by hugging them!

### PR DESCRIPTION
**Pull request by Zarthus**
hug.py, cheer someone up by giving them a hug.

This command sends a hug to `username`, if `username` is not specified, we assume everyone is going to get some sweet, tender loving.

### CODE REVIEW

**Comment by daboross** [comment]
This is pretty nice. Do you think you could possibly merge it into attacks.py as well, as it kind of fits with what's in there?

**Comment by Zarthus** [comment]
@daboross Do you think `cake.py`, `slap.py`, and `kill.py` should undergo the same fate?

**Comment by daboross** [comment]
@Zarthus They already have in refresh, mostly

**Comment by Techman** [comment]
No! Don't mess with my beloved cake! :disappointed_relieved:

**Comment by neersighted** [comment]
:+1:

**Pull request closed without merging**
