### PR TITLE
allow these functions to have custom targets, with the default being the...

### PR DESCRIPTION
**Pull request by antdking**
... person who called it

### CODE REVIEW

**Comment by antdking** [comment]
untested btw

**Comment by dmptrluke** [comment]
I'll pull this after I have time to test it!

**Comment by BlaneyXYZ** [comment]
I don't think this works :( It caused my main.py to error on start up

**Comment by antdking** [comment]
ah sorry, I know the error. kwargs should go last :/
just tested it, and it's working

**Pull request closed without merging**
