### PR TITLE
Add 'listfactoids' command to list all factoids

### PR DESCRIPTION
**Pull request by daboross**
Adds a .listfactoids command to list factoids

### CODE REVIEW

**Comment by literalplus** [comment]
The permissions for the other commands are `addfactoid` and `delfactoid`. Why is this `adminonly`? Wouldn't `listfactoids` make more sense/be more consistent?

**Comment by daboross** [comment]
@xxyy Yep, fixed.

**Comment by urbels** [comment]
yay

**Comment by literalplus** [comment]
Any updates on this? Would really love to see this feature.

**Pull request merged**
