### PR TITLE
Rewrote twitter.py to work with Api v1.1

### PR DESCRIPTION
**Pull request by KsaRedFx**
Rewrote Twitter.py to work with the new Twitter API v1.1
Requires 4 API Keys from Twitter

Will possibly update in the future to include Hashtags and Replies

### CODE REVIEW

**Comment by urbels** [comment]
yay

**Comment by KsaRedFx** [comment]
Yep! Now it just needs to get Pull'd

**Comment by KsaRedFx** [comment]
@lukeroge @neersighted Any chance of pulling this? 
Or let me know why you won't accept it

**Comment by urbels** [comment]
I think he not reviewed yet

**Comment by blha303** [comment]
At https://github.com/ClouDev/CloudBot/pull/71/files#L2R5 That doesn't work if the system doesn't have simplejson. I'd use:

```
try:
    import json
except ImportError:
    import simplejson as json
```

**Comment by blha303** [comment]
I tried to set up this plugin on my bot xD, it didn't work. I think the python-twitter plugin is out-of-date, but I might have just not set it up right.

**Comment by KsaRedFx** [comment]
python-twitter is not out of date. This is running on:
-  irc.Esper.net - Crow2
-  irc.Snoonet.org: Crow
-  irc.OSPnet.org: Crow
-  irc.Ewnix.net: Crow  

try pip install python-twitter --upgrade

**Comment by KsaRedFx** [comment]
Your code is a little backwards, by the way, You'd want

``` python
try: 
    import simplejson as json
except:
    import json
```

I'll add this to my pull

**Comment by dmptrluke** [comment]
So I was playing around with some code and ended up with 696f2b7
Sorry! D:

**Pull request closed without merging**
