### PR TITLE
Updating .mcstatus to fix colors

### PR DESCRIPTION
**Pull request by blha303**
<dl>
<dt>Before</dt>
</dl>

**Irssi**
Before - Irssi

**Hexchat**
Before - Hexchat

<dl>
<dt>After</dt>
</dl>

**Irssi**
After - Irssi

**Hexchat**
After - Hexchat

### CODE REVIEW

**Comment by neersighted** [comment]
Heh, thanks, never noticed that (not my code (tm))!

**Comment by neersighted** [comment]
One things though.  It was intended with it all be black (well, default), with only the words 'online' and 'offline' colors (such as it appeared before in HexChat).  Could you put it back so that it appears that way in all clients?

**Comment by blha303** [comment]
Yeah, It appeared differently for me in Irssi, so I jumped in and changed that. I'll fix it now.

**Comment by blha303** [comment]
**Irssi:**
Irssi

**Hexchat:**
Hexchat

**Comment by neersighted** [comment]
Thanks!

**Pull request merged**
