### PR TITLE
portal2sounds.com has banned Cloudbot's user agent.

### PR DESCRIPTION
**Pull request by blha303**

### CODE REVIEW

**Comment by LaxWasHere** [comment]
What an evil website.

**Comment by blha303** [comment]
I can probably cache their data.

**Comment by pushrax** [comment]
If we did, it was an accident, I swear!

edit: it was probably CloudFlare actually.

**Comment by blha303** [comment]
:o It might have been. Anyway, I made a sweet REST-like api for the data, at http://p2sounds.blha303.com.au

**Pull request merged**
